version: '3.8'
services:
  db:
    image: postgres:15
    container_name: planner_db_container
    environment:
      POSTGRES_DB: planner_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: planner123
    ports:
      - "5434:5432"